#!/usr/bin/env bash -e
app=$(basename $0)

# defining c9 working dir
c9d="${HOME}/.c9env-init"

# exit if we DID this before
test -f ${c9d}/_${app}.done && { echo "== log $0: we DID it before; exiting" ; exit 0 ; }

# if there is no dir, remove such a file if it exists and create dir
test -d ${c9d} || { rm -fr ${c9d} ; mkdir ${c9d} ; echo "== log $0: created dir: ${c9d}" ; }

# clone repo - only once
test -f ${c9d}/_${app}.done-clone || {
rm -fr ${c9d}/cloud9init
git clone https://github.com/FreeIaC/cloud9init.git ${c9d}/cloud9init
touch ${c9d}/_${app}.done-clone

echo "== log $0: git repo cloned to ${c9d}/cloud9init"
}

# create temporal init and make it executable
cat <<EOF > ${c9d}/init~
#!/usr/bin/env bash -e

cd ${c9d}
find cloud9init/scripts -name "[0-9][0-9][0-9]-*" -print0 | sort -z |  xargs -n 1 -0 -I% bash -c 'bash %'
EOF

chmod +x ${c9d}/init~

# mark that we DONE this
touch ${c9d}/_${app}.done

# persist init
mv ${c9d}/init~ ${c9d}/init
