#!/usr/bin/env bash -e
test -f ./_done_${0} && exit 0

cat <<EOF >> ~/.bash_aliases
alias ll='ls -la'
EOF

cat <<EOF >> ~/.bashrc
if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi
EOF

touch ./_done_${0}
