#!/usr/bin/env bash -e
wd=$(pwd)
app=$(basename $0)
test -f ${wd}/_${app}.done && { echo "== log $0: we DID it, exiting" ; exit 0 ; }

cat <<EOF >> ~/.bash_aliases
alias ll='ls -la'
EOF

cat <<EOF >> ~/.bashrc
if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi
EOF

touch ${wd}/_${app}.done

echo "== log $0: bash aliases created"
