#!/usr/bin/env bash -e
wd=$(pwd)
app=$(basename $0)
test -f ${wd}/_${app}.done && { echo "== log $0: we DID it, exiting" ; exit 0 ; }

cat <<EOF >> ~/.bashrc
if [ -f  ${wd}/.c9env ]; then
  .  ${wd}/.c9env
fi
EOF

> ${wd}/.c9env

touch ${wd}/_${app}.done
