#!/usr/bin/env bash -e
wd=$(pwd)
app=$(basename $0)
test -f ${wd}/_${app}.done && { echo "== log $0: we DID it, exiting" ; exit 0 ; }

python3 -m pip install --user --upgrade pip awscli boto3

touch ${wd}/_${app}.done

hash -r
aws --version
