#!/usr/bin/env bash -e
test -f ./_done_${0} && exit 0

export instance_id=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
sudo yum update && sudo yum -y install jq
export region=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r '.region')

python3 -c "import boto3
import os
from botocore.exceptions import ClientError
region=os.getenv('region')
ec2 = boto3.client('ec2', region_name=region)
volume_info = ec2.describe_volumes(
    Filters=[
        {
            'Name': 'attachment.instance-id',
            'Values': [
                os.getenv('instance_id')
            ]
        }
    ]
)
volume_id = volume_info['Volumes'][0]['VolumeId']
try:
    resize = ec2.modify_volume(
            VolumeId=volume_id,
            Size=30
    )
    print(resize)
except ClientError as e:
    if e.response['Error']['Code'] == 'InvalidParameterValue':
        print('ERROR MESSAGE: {}'.format(e))"

if [ $? -eq 0 ]; then
    touch ./_done_${0}
    echo "ok: Disk size is increased, rebooting..."
    sudo reboot
else
    echo "error: Something went wrong !!!"
fi
