#!/usr/bin/env bash -e
wd=$(pwd)
app=$(basename $0)
test -f ${wd}/_${app}.done && { echo "== log $0: we DID it, exiting" ; exit 0 ; }

install_krew () {
  local dir=$(mktemp -d)
  cd $dir
  OS="$(uname | tr '[:upper:]' '[:lower:]')"
  ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')"
  curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/krew.tar.gz"
  tar zxvf krew.tar.gz
  KREW=./krew-"${OS}_${ARCH}"
  "$KREW" install krew
  cd -
  rm -fr $dir
}

install_krew

export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

cat <<'EOF' >> ~/.bashrc
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
EOF

kubectl krew update
kubectl krew install ctx
kubectl krew install ns

alias kx='kubectl ctx'
alias kn='kubectl ns'

cat <<'EOF' >> ~/.bash_aliases
alias kx='kubectl ctx'
alias kn='kubectl ns'
EOF

touch ${wd}/_${app}.done
