#!/usr/bin/env bash -e
wd=$(pwd)
app=$(basename $0)

if [ -f ${wd}/.c9env ]; then
  . ${wd}/.c9env
fi

key_arn=$(aws kms describe-key --key-id alias/${KMS_KEY_NAME} --query KeyMetadata.Arn --output text --region ${AWS_REGION} 2>/dev/null)

test echo ${key_arn} | grep -q "arn:aws:kms" || {
  # TODO: add tag: 'project: new-gaming-2'
  aws kms create-alias --alias-name alias/${KMS_KEY_NAME} --target-key-id $(aws kms create-key --query KeyMetadata.Arn --output text --region ${AWS_REGION}) --region ${AWS_REGION}
}
