#!/usr/bin/env bash -e
app=$(basename $0)

# working dir
c9d="${HOME}/.c9env-init"

# exit if we DID this before
test -f ${c9d}/_${app}.done && exit 0

# if there is no dir, remove such a file if it exists and create dir
test -d ${c9d} || { rm -fr ${c9d} ; mkdir ${c9d} ; }

# add init to .bashrc - only once
test -f ${c9d}/_${app}.done-bashrc || {
cat <<EOF >> ${HOME}/.bashrc && touch ${c9d}/_${app}-done-bashrc
if [ -x ${c9d}/init ]; then
  bash ${c9d}/init
fi
EOF
}

# clone repo - only once
test -f ${c9d}/_${app}.done-clone || {
rm -fr ${c9d}/cloud9init
git clone https://github.com/FreeIaC/cloud9init.git ${c9d}/cloud9init
touch ${c9d}/_${app}.done-clone
}

# create temporal init and make it executable
cat <<EOF > ${c9d}/init~
#!/usr/bin/env bash -e

cd ${c9d}
find -s cloud9init/scripts -name "[1-9][0-9][0-9]-*" -exec bash ls -1 \;
EOF

chmod +x ${c9d}/init~

# mark that we DONE this
touch ${c9d}/_${app}.done

# persist and run init
mv ${c9d}/init~ ${c9d}/init
bash ${c9d}/init
