#!/usr/bin/env bash -e
workdir=$(pwd)
echo "== log $0: workdir: $workdir"

app=$(basename $0)
echo "== log $0: app: $app"

test -f ${workdir}/_${app}.done && { echo "== log $0: workdir: $workdir; app: $app; we DID it, exiting" ; exit 0 ; }

echo "== log $0: bash aliases: $0"

touch ${workdir}/_${app}.done
